# Generated by Django 5.2.6 on 2025-09-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department', 'study_year', 'semester', 'course_type', 'name'], 'verbose_name': 'مقرر', 'verbose_name_plural': 'المقررات'},
        ),
        migrations.AlterModelOptions(
            name='coursefile',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'ملف مقرر', 'verbose_name_plural': 'ملفات المقررات'},
        ),
        migrations.AlterModelOptions(
            name='coursetype',
            options={'ordering': ['name'], 'verbose_name': 'نوع مقرر', 'verbose_name_plural': 'أنواع المقررات'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['order'], 'verbose_name': 'فصل', 'verbose_name_plural': 'الفصول'},
        ),
        migrations.AlterModelOptions(
            name='studyyear',
            options={'ordering': ['year'], 'verbose_name': 'سنة دراسية', 'verbose_name_plural': 'السنوات الدراسية'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.coursetype', verbose_name='نوع المقرر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المقرر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.semester', verbose_name='الفصل'),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.studyyear', verbose_name='السنة الدراسية'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.course', verbose_name='المقرر'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='file',
            field=models.FileField(upload_to='course_files/%Y/%m/%d/', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='file_size',
            field=models.BigIntegerField(verbose_name='حجم الملف (بايت)'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='file_type',
            field=models.CharField(max_length=100, verbose_name='نوع الملف'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='original_filename',
            field=models.CharField(max_length=255, verbose_name='اسم الملف الأصلي'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(choices=[('practical', 'عملي'), ('theoretical', 'نظري')], max_length=20, unique=True, verbose_name='نوع المقرر'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='الفصل'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='order',
            field=models.IntegerField(unique=True, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='year',
            field=models.IntegerField(unique=True, verbose_name='السنة الدراسية'),
        ),
    ]
