# Generated by Django 5.2.6 on 2025-09-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_coursefile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('subscriber_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.department')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.coursefile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.semester')),
                ('study_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.studyyear')),
            ],
            options={
                'indexes': [models.Index(fields=['acknowledged', 'created_at'], name='courses_not_acknowl_d97ecf_idx'), models.Index(fields=['department', 'study_year', 'semester'], name='courses_not_departm_928589_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.semester')),
                ('study_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.studyyear')),
            ],
            options={
                'indexes': [models.Index(fields=['telegram_user_id'], name='courses_sub_telegra_146402_idx'), models.Index(fields=['department', 'study_year', 'semester'], name='courses_sub_departm_b874fa_idx')],
                'unique_together': {('telegram_user_id', 'department', 'study_year', 'semester')},
            },
        ),
    ]
