# Generated by Django 5.2.11 on 2026-03-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_notification_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subscriber_ids',
            field=models.JSONField(blank=True, default=list, help_text='قائمة بأرقام المشتركين (اتركه فارغاً)', null=True),
        ),
    ]
