# Generated by Django 5.2.11 on 2026-03-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_notification_subscriber_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('create', 'إضافة'), ('update', 'تعديل')], default='create', max_length=20),
        ),
    ]
